spring:
  config:
    activate:
      on-profile: prod
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

jdeploy:
  artifact:
    uml-output-path: ${JDEPLOY_UML_OUTPUT_PATH:examples/prod-uml}
