spring:
  config:
    activate:
      on-profile: dev
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:dev-password}

jdeploy:
  artifact:
    uml-output-path: ${JDEPLOY_UML_OUTPUT_PATH:examples/dev-uml}
